
:token = 

GET http://localhost:8082/intern/user/lookup?key=SHA256:i%2BUd3rH5q16tUNdfzGxq20fYYfegE9ef0HhP5sl2LIs
Authorization: Bearer :token

#
# List public repositories
#

GET http://localhost:8082/repos/public

#
# List repositories shared with logged-in user
#

GET http://localhost:8082/repos/shared
Authorization: Bearer :token

#
# List repositories for a user
#

GET http://localhost:8082/users/gicmo/repos
Authorization: Bearer :token


#
# Browse repo
#

GET http://localhost:8082/users/gicmo/repos/exrepo/browse/master


#
# Get Branch
#

GET http://localhost:8082/users/gicmo/repos/exrepo/branches/master
Authorization: Bearer :token

#
# Get Object (commit object)
#

GET http://localhost:8082/users/gicmo/repos/exrepo/objects/ac6e8e456c01ee7193633b34b9554a3095cfe78a
Authorization: Bearer :token

#
# Get Object (tree)
#

GET http://localhost:8082/users/gicmo/repos/exrepo/objects/2ef26eab63d0a09c9a53ad5df01701396e72c3f4
Authorization: Bearer :token

#
# Get Visibility
#

GET http://localhost:8082/users/gicmo/repos/exrepo/visibility
Authorization: Bearer :token

#
# Set Visibility
#

PUT http://localhost:8082/users/gicmo/repos/exrepo/visibility
Authorization: Bearer :token
Content-Type: application/json

{
        "visibility": "public"
}
