language: go
sudo: required
dist: trusty

services:
  - docker

go:
  - 1.7
  - tip

before_install:
  - sudo apt-get update
  - sudo apt-get install git-annex
  - sudo apt-get install python-pip
  - pip install pyyaml
  - pushd contrib && ./hostkey.sh && popd
  - docker build -t gin-repod .

install:
  - go get "github.com/docopt/docopt-go"
  - go get "github.com/gorilla/mux"
  - go get "github.com/gorilla/handlers"
  - go get "github.com/dgrijalva/jwt-go"
  - go get "golang.org/x/crypto/ssh"
  - go get "github.com/fsouza/go-dockerclient"
  # coveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

after_success:
  - if [ $TRAVIS_GO_VERSION == "tip" ]; then exit 0; fi
  - if [ -z ${DOCKER_PASS+x} ]; then echo "No DOCKER_PASS set."; exit 0; fi
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" || exit 1
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      if ["TRAVIS_BRANCH" == "master" ]; then
        export TAG="latest";
      else
        export TAG="$TRAVIS_BRANCH";
      fi

      docker tag gin-repod:latest gnode/gin-repo:$TAG || exit 1;
    fi
  - docker tag gin-repod:latest gnode/gin-repo:travis-$TRAVIS_BUILD_NUMBER
  - docker push gnode/gin-repo
  # create coverage profile for all packages providing tests
  - echo "mode: count" > profile.cov;
    for Dir in $(go list ./...);
    do
      currDir=$(echo $Dir | sed 's/github.com\/G-Node\/gin-repo\///g');
      currCount=$(ls -l $currDir/*.go 2>/dev/null | wc -l);
      if [ $currCount -gt 0 ];
      then
        go test -covermode=count -coverprofile=tmp.out $Dir;
        if [ -f tmp.out ];
        then
          cat tmp.out | grep -v "mode: count" >> profile.cov;
        fi
      fi
    done
  # upload coverage profile to coveralls
  - goveralls -coverprofile=profile.cov -service=travis-ci
