language: go
sudo: required

services:
  - docker

go:
  - 1.7
  - tip

before_install:
  - pushd contrib && ./hostkey.sh && popd
  - docker build -t gin-repod .

install:
  - go get "github.com/docopt/docopt-go"
  - go get "github.com/gorilla/mux"
  - go get "github.com/gorilla/context"
  - go get "github.com/gorilla/handlers"
  - go get "github.com/dgrijalva/jwt-go"
  - go get "golang.org/x/crypto/ssh"
  - go get "github.com/fsouza/go-dockerclient"
